/*CREATE DATABASE IF NOT EXISTS debug_green;
USE debug_green;

DROP TABLE IF EXISTS offer;
CREATE TABLE offer (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 green_id BIGINT UNSIGNED  NOT NULL,
 salary_id BIGINT UNSIGNED,
 company_id BIGINT UNSIGNED NOT NULL,
 updated_flg INT(1) DEFAULT 0,
 title TEXT NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX idx_offer_green_id ON offer(green_id);

DROP TABLE IF EXISTS salary;
CREATE TABLE salary (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 description VARCHAR(128) UNIQUE NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS offer_site;
CREATE TABLE offer_site (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 offer_id BIGINT UNSIGNED NOT NULL,
 site_id BIGINT UNSIGNED NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS site;
CREATE TABLE site (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 description VARCHAR(128) UNIQUE NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS offer_detail;
CREATE TABLE offer_detail (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 offer_id INT UNSIGNED NOT NULL,
 title_id INT UNSIGNED NOT NULL,
 description TEXT NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX idx_offer_detai_offer_id ON offer_detail (offer_id);

DROP TABLE IF EXISTS offer_detail_title;
CREATE TABLE offer_detail_title (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 description VARCHAR(128) UNIQUE NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS company;
CREATE TABLE company (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 green_id INT UNSIGNED UNIQUE,
 name TEXT NOT NULL,
 short_description TEXT NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS offer_company;
CREATE TABLE offer_company (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 offer_id BIGINT UNSIGNED NOT NULL,
 title_id BIGINT UNSIGNED NOT NULL,
 description TEXT NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS offer_company_title;
CREATE TABLE offer_company_title (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 description VARCHAR(128) NOT NULL UNIQUE,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
 
DROP TABLE IF EXISTS apply;
CREATE TABLE apply (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 offer_id BIGINT UNSIGNED NOT NULL,
 title_id BIGINT UNSIGNED NOT NULL,
 description TEXT NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
 
DROP TABLE IF EXISTS apply_title;
CREATE TABLE apply_title (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 description VARCHAR(128) NOT NULL UNIQUE,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS other;
CREATE TABLE other (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 offer_id BIGINT UNSIGNED NOT NULL,
 title_id BIGINT UNSIGNED NOT NULL,
 description TEXT,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS other_title;
CREATE TABLE other_title (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 description VARCHAR(128) NOT NULL UNIQUE,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS offer_tag;
CREATE TABLE offer_tag (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 offer_id BIGINT UNSIGNED,
 tag_id BIGINT UNSIGNED NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS tags;
CREATE TABLE tags (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 tag VARCHAR(128) UNIQUE NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

*/

DROP TABLE IF EXISTS offer_keywords;
CREATE TABLE offer_keywords (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 offer_id BIGINT UNSIGNED,
 keyword_id BIGINT UNSIGNED NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS keywords;
CREATE TABLE keywords (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 keyword VARCHAR(128) UNIQUE NOT NULL,
 created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 modified TIMESTAMP DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
